rebuilt with autoconf 2.53

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1689,6 +1689,7 @@ benchmarks demos"
 
 
 
+
 # Set default values
 AR_FLAGS="-cru"
 
@@ -2129,11 +2130,11 @@ case "$target" in
     case "$CXX" in
       g++)
     		echo "Linux: assuming g++/g77"
-        F77=g77
+        F77="g77 -fno-second-underscore"
         F77_OPTIMIZE_FLAGS="-O2 -funroll-loops"
-        F90=g77
-        F90_OPTIMIZE_FLAGS="-O2 -funroll-loops"
-        CXXFFLAGS="-DBZ_FORTRAN_SYMBOLS_WITH_DOUBLE_TRAILING_UNDERSCORES"
+        F90=""
+        F90_OPTIMIZE_FLAGS=""
+        CXXFFLAGS="-DBZ_FORTRAN_SYMBOLS_WITH_TRAILING_UNDERSCORES"
         FORTLIBS="-lg2c"
       ;;
       icc)
@@ -2143,7 +2144,9 @@ case "$target" in
         F90=ifc
         F90_OPTIMIZE_FLAGS="-O2"
         CXXFFLAGS="-DBZ_FORTRAN_SYMBOLS_WITH_TRAILING_UNDERSCORES"
-        FORTLIBS="-lF90 -lCEPCF90 -lIEPCF90 -lintrins"
+# To fix to find automatically the correct -L for fortran 90 libs and libg2c
+#        FORTLIBS="-L/opt/intel/compiler60/ia32/lib -lF90 -lCEPCF90 -lIEPCF90 -lintrins -L/usr/lib/gcc-lib/i386-redhat-linux/2.96 -lg2c"
+        FORTLIBS="-lF90 -lCEPCF90 -lIEPCF90 -lintrins -lg2c"
       ;;
     esac
   ;;
@@ -2196,6 +2199,21 @@ building fortran benchmarks, and performance may be unexciting.
 EOF
   ;;
 esac
+
+if test ! x"$F90" = x; then
+	CXXF90FLAG="-DFORTRAN_90"
+fi
+
+
+if test ! x"$F90" = x; then
+  F90_COMPILER_TRUE=
+  F90_COMPILER_FALSE='#'
+else
+  F90_COMPILER_TRUE='#'
+  F90_COMPILER_FALSE=
+fi
+
+
 
 # Check if the script was called with --enable-optimize or
 # --enable-debug, and if so modify the compilation flags.
@@ -3141,7 +3159,7 @@ if test "${ac_cv_lib_blas_daxpy_+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lblas  $LIBS"
+LIBS="-lblas $FORTLIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -3203,7 +3221,7 @@ if test "${ac_cv_lib_blas_daxpy+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lblas  $LIBS"
+LIBS="-lblas $FORTLIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -3265,7 +3283,7 @@ if test "${ac_cv_lib_blas_DAXPY+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lblas  $LIBS"
+LIBS="-lblas $FORTLIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -3327,7 +3345,7 @@ if test "${ac_cv_lib_blas_daxpy__+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lblas  $LIBS"
+LIBS="-lblas $FORTLIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -3379,7 +3397,7 @@ echo "${ECHO_T}$ac_cv_lib_blas_daxpy__" >&6
 if test $ac_cv_lib_blas_daxpy__ = yes; then
    CXX_OPTIMIZE_FLAGS="$CXX_OPTIMIZE_FLAGS -DUSE_LIBBLAS"
      CXXFFLAGS="-DBZ_FORTRAN_SYMBOLS_WITH_DOUBLE_TRAILING_UNDERSCORES"
-     BLASLIB="$BLASPATH -lblas"
+     BLASLIB="$FORTLIBS $BLASPATH -lblas"
 fi
 
 
@@ -3398,6 +3416,7 @@ echo "CXX                = $CXX"
 echo "CXXFLAGS           = $CXXFLAGS"
 echo "CXX_OPTIMIZE_FLAGS = $CXX_OPTIMIZE_FLAGS"
 echo "CXX_DEBUG_FLAGS    = $CXX_DEBUG_FLAGS"
+echo "CXXFFLAGS          = $CXXFFLAGS"
 echo "F77                = $F77"
 echo "F77_OPTIMIZE_FLAGS = $F77_OPTIMIZE_FLAGS"
 echo "F90                = $F90"
@@ -3516,6 +3535,13 @@ DEFS=`sed -n -f confdef2opt.sed confdefs.h | tr "$ac_LF_and_DOT" ' .'`
 rm -f confdef2opt.sed
 
 
+if test -z "${F90_COMPILER_TRUE}" && test -z "${F90_COMPILER_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"F90_COMPILER\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"F90_COMPILER\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${AMDEP_TRUE}" && test -z "${AMDEP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"AMDEP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -4069,6 +4095,9 @@ s,@BLASLIB@,$BLASLIB,;t t
 s,@AR@,$AR,;t t
 s,@AR_FLAGS@,$AR_FLAGS,;t t
 s,@RANLIB@,$RANLIB,;t t
+s,@CXXF90FLAG@,$CXXF90FLAG,;t t
+s,@F90_COMPILER_TRUE@,$F90_COMPILER_TRUE,;t t
+s,@F90_COMPILER_FALSE@,$F90_COMPILER_FALSE,;t t
 s,@ac_ct_AR@,$ac_ct_AR,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@CXX@,$CXX,;t t
